name: Beyond melee

collections_dir: collections

collections:
    characters:
        output: false
    faqs:
        output: false
    credits:
        output: false
    balance:
        output: false
    support:
        output: false