name: Beyond melee

collections_dir: collections

excerpt_separator: <!--more-->

collections:
    characters:
        output: false
    faqs:
        output: false
    credits:
        output: false
    balance:
        output: false
    support:
        output: false
    features:
        output: false
        order:
            - fay.md
            - skullkid.md
            - raichu.md
            - wolf.md
            - smewtwo.md
            - rebalance.md
            - controls.md
            - stages.md
            - modes.md
    posts:
        output: true
        permalink: /devblog/:categories/:year/:month/:day/:title/
